{% set version = "0.4" %}


package:
  name: lazy-loader
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lazy_loader/lazy_loader-{{ version }}.tar.gz
  sha256: 47c75182589b91a4e1a85a136c074285a5ad4d9f39c63e0d7fb76391c4574cd1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit-core >=3.7,<4
    - python >=3.7
    - packaging
    - importlib-metadata
  run:
    - python >=3.7
    - packaging
    - importlib-metadata

test:
  imports:
    - lazy_loader
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: lazy-loader
    # A conflict was created for older lazy_loader packages
    # version 0.4.0 build 0 and older
    # https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/815
    # so that they cannot be co-installed with lazy-loader
  - name: lazy_loader
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('lazy-loader', exact=True) }}
    test:
      imports:
        - lazy_loader

about:
  home: https://pypi.org/project/lazy-loader/
  summary: Easily load subpackages and functions on demand
  license: BSD-3-Clause
  license_file: LICENSE.md
  description: |
    `lazy-loader` makes it easy to load subpackages and functions on demand.

    PyPI: https://pypi.org/project/lazy-loader/

  doc_url: https://github.com/scientific-python/lazy-loader
  dev_url: https://github.com/scientific-python/lazy-loader

extra:
  recipe-maintainers:
    - bsipocz
    - sugatoray
    - bmcfee
