{% set name = "lazy_loader" %}
{% set version = "0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lazy_loader-{{ version }}.tar.gz
  sha256: 47c75182589b91a4e1a85a136c074285a5ad4d9f39c63e0d7fb76391c4574cd1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit-core >=3.7,<4
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - lazy_loader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lazy_loader/
  summary: Easily load subpackages and functions on demand
  license: BSD-3-Clause
  license_file: LICENSE.md
  description: |
    `lazy-loader` makes it easy to load subpackages and functions on demand.

    PyPI: [https://pypi.org/project/lazy_loader/](https://pypi.org/project/lazy_loader/)

  doc_url: https://github.com/scientific-python/lazy_loader
  dev_url: https://github.com/scientific-python/lazy_loader

extra:
  recipe-maintainers:
    - bsipocz
    - sugatoray
    - bmcfee
